server:
  port: 8081
  servlet:
    context-path: /shiro-test
mybatis:
  type-aliases-package: com.example.springbootshiro.business.system.domain
  configuration:
    map-underscore-to-camel-case=true: true
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 19921209
project:
  doc:
    enable: true